# Generated by Django 5.0.1 on 2024-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_rename_ordert_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
