# Generated by Django 5.0.1 on 2024-02-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_order_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Shoes'), (3, 'Cloths'), (4, 'Laptops'), (5, 'Watches'), (6, 'Fridges')], verbose_name='category'),
        ),
    ]
